reformat files

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -2,33 +2,33 @@ name: Release-Please
 
 # triggered when tests complete on main branch
 on:
-  workflow_run:
-    workflows:
-      - "Test"
-    branches:
-      - main
-    types:
-      - completed
+    workflow_run:
+        workflows:
+            - "Test"
+        branches:
+            - main
+        types:
+            - completed
 
 jobs:
-  refused:
-    # Do not release if tests failed
-    runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'failure'}}
-    steps:
-      - id: refused_step
-        run: exit 1
+    refused:
+        # Do not release if tests failed
+        runs-on: ubuntu-latest
+        if: ${{ github.event.workflow_run.conclusion == 'failure'}}
+        steps:
+            -   id: refused_step
+                run: exit 1
 
-  release-please:
-    # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
-    name: Prepare next release
-    runs-on: ubuntu-latest
-    # release only if tests pass
-    if: ${{ github.event.workflow_run.conclusion == 'success'}}
-    steps:
-      - uses: GoogleCloudPlatform/release-please-action@v2
-        with:
-          token: ${{ secrets.GH_TOKEN }}
-          release-type: python
-          package-name: dsp-tools
-          changelog-types: '[{"type": "feat", "section": "Enhancements", "hidden": false }, {"type": "fix", "section": "Bug Fixes", "hidden": false }, {"type": "chore", "section": "Maintenance", "hidden": false }, {"type": "refactor", "section": "Maintenance", "hidden": false }, {"type": "docs", "section": "Documentation", "hidden": false }]'
+    release-please:
+        # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
+        name: Prepare next release
+        runs-on: ubuntu-latest
+        # release only if tests pass
+        if: ${{ github.event.workflow_run.conclusion == 'success'}}
+        steps:
+            -   uses: GoogleCloudPlatform/release-please-action@v2
+                with:
+                    token: ${{ secrets.GH_TOKEN }}
+                    release-type: python
+                    package-name: dsp-tools
+                    changelog-types: '[{"type": "feat", "section": "Enhancements", "hidden": false }, {"type": "fix", "section": "Bug Fixes", "hidden": false }, {"type": "chore", "section": "Maintenance", "hidden": false }, {"type": "refactor", "section": "Maintenance", "hidden": false }, {"type": "docs", "section": "Documentation", "hidden": false }]'
